### ISSUE TITLE
Clean up Make files

### ISSUE THREAD

**Issue by finsberg** [ComputationalPhysiology/goss#3]
There are a lot of CMakefiles that has to be updated.

In particular we have a few old cmake policies
https://github.com/ComputationalPhysiology/goss/blob/master/CMakeLists.txt#L20-L22

and probably a few other departed statements.

**Comment by KGHustad** [comment]
I think most of these policies can be removed, but it may require changes elsewhere. In general, I don't think maintaining compatibility with old versions of CMake is that important, given that it is fairly easy to download a recent version CMake on most systems. I'm happy to take a look at it over the weekend.

**Comment by KGHustad** [comment]
[CMP0003](https://cmake.org/cmake/help/latest/policy/CMP0003.html) should be safe to remove without any further changes since the new behaviour is the default.

I'm not really sure about all of the SWIG stuff. 

It seems like we can only install to `/usr/local/` at the moment because the Python interface needs to find the goss shared library. It would be nice to be able to install Goss to a conda environment.
